
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (//bg-gradient-to-r from-slate-50 to-blue-300
    <html lang="en">
      <body className=" bg-scroll " suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
